<?php
include('config.php');
include('header.php'); // Include header

// Example: Class size report
$sql = "SELECT c.ClassName, COUNT(e.StudentID) as NumberOfStudents FROM Class c JOIN Enrollment e ON c.ClassID = e.ClassID GROUP BY c.ClassID";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
    echo "<table><tr><th>Class</th><th>Number of Students</th></tr>";
    while ($row = $result->fetch_assoc()) {
        echo "<tr><td>" . $row['ClassName'] . "</td><td>" . $row['NumberOfStudents'] . "</td></tr>";
    }
    echo "</table>";
} else {
    echo "No data found.";
}

include('footer.php'); // Include footer
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generate Reports</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <h1>Reports Dashboard</h1>
    <!-- Reports generated by PHP script will be displayed here -->
</body>
</html>

